
- action: "Push to https://github.com/bha8141/mavenbuild.git"
  type: "PUSH"
  login: "snehithaanpur456@gmail.com"
  password: "LiveLifeLove@81"
  push_tags: false
  git_auth_mode: "HTTP"
  target_branch: "$develop"
  push_url: "https://github.com/bha8141/mavenbuild.git"
  comment: "$BUDDY_EXECUTION_ID"
  tag: "tagName"
  deployment_excludes:
  - "/tmp/"
  trigger_condition: "ALWAYS"
  use_custom_gitignore: true
  without_force: false