# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

steps:
- checkout: self
  persistCredentials: true

- script:
    git remote add https://github.com/snehithaanpur/MavenBuild.git
    git push https://{7ebe2bb4948c33006f8f661bd44256c5dc51af5d}github.com/snehithaanpur/MavenBuild.git HEAD:master
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
