# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: 
    git config --global user.name "SnehithaAnpur"
    git config --global user.email "snehithaanpur456@gmail.com" 
    git remote add new "https://github.com/snehithaanpur/MavenBuild.git"
    git push new master

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
