# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml


trigger:
- develop

steps:
- checkout: self
  persistCredentials: true
- script:
    git config --global user.name "snehithaanpur"
    git config --global user.email "snehithaanpur456@gmail.com"
    git add remote new "github.com/snehithaanpur/gitrepo.git"
    git push new HEAD:master

          

